# Generated by Django 4.1.1 on 2022-11-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=150)),
                ('description', models.CharField(db_column='description', max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('deleted', models.BooleanField(db_column='deleted')),
            ],
            options={
                'db_table': 'chat_room',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(db_column='message_text', max_length=250)),
                ('created_date', models.DateTimeField(auto_now=True, db_column='created_date')),
                ('deleted', models.BooleanField(db_column='deleted')),
                ('chat_room', models.ForeignKey(db_column='chat_room', on_delete=django.db.models.deletion.CASCADE, to='chatroom.chatroom')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
