# Generated by Django 4.1.1 on 2022-11-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_chatroom_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='deleted',
            field=models.BooleanField(db_column='deleted', default=False),
        ),
    ]
